# Generated by Django 5.1.7 on 2025-04-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='صورة التصنيف')),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('trip_name', models.CharField(max_length=255)),
                ('trip_location', models.CharField(max_length=255)),
                ('trip_phone', models.CharField(max_length=20)),
                ('trip_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الرحلة')),
                ('location', models.CharField(default='Default Location', max_length=200, verbose_name='موقع الرحلة')),
                ('responsible_phone', models.CharField(max_length=20, verbose_name='هاتف المسؤول')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration', models.CharField(max_length=50, verbose_name='المدة')),
                ('capacity', models.PositiveIntegerField(verbose_name='السعة')),
                ('image', models.ImageField(upload_to='trips/', verbose_name='الصورة')),
                ('date', models.DateTimeField(verbose_name='تاريخ الرحلة')),
                ('actve', models.BooleanField(default=True, verbose_name='مفعل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trips.category')),
            ],
        ),
    ]
